# Generated by Django 3.2.2 on 2021-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='Окончание обучения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='certificates',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='name',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='study',
            name='Начало обучения',
            field=models.DateField(blank=True, null=True),
        ),
    ]
