# Generated by Django 3.2.2 on 2021-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projects_имя проекта'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='Имя серитификата',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
