# Generated by Django 3.2.2 on 2021-05-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_certificates_имя серитификата'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='Имя серитификата',
            new_name='name_certif',
        ),
        migrations.RenameField(
            model_name='himself',
            old_name='О себе',
            new_name='himself',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Имя проекта',
            new_name='name_proj',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Описание',
            new_name='study_center',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Начало обучения',
            new_name='study_date',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Окончание обучения',
            new_name='study_finish_date',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Название заведения',
            new_name='study_head',
        ),
    ]
