# Generated by Django 3.0.7 on 2021-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210526_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
